// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    var Watcher, bill, bob;
    Watcher = (function() {

      function Watcher(name) {
        this.name = name;
      }

      Watcher.prototype.sayHi = function(toName) {
        return $('#results').append("" + this.name + " says hello to " + toName + "</br>");
      };

      Watcher.prototype.watch = function(buttonId) {
        var _this = this;
        return $('#' + buttonId).click(function(e) {
          var toname;
          toname = $('#name').val();
          return _this.sayHi(toname);
        });
      };

      return Watcher;

    })();
    bill = new Watcher('Bill');
    bill.watch('button1');
    bob = new Watcher('Bob');
    bob.watch('button1');
    bill.watch('button2');
    return bill.name = 'William';
  });

}).call(this);
